image: gitpod/workspace-full

tasks:
  - name: Install avn CLI
    init: pip install aiven-client
  - name: Open Readme
    init: gp open README.md
  - name: Open Producer
    init: gp open src/main/java/org/example/ProducerMultipleMessages.java
  - name: Open Consumer
    init: gp open src/main/java/org/example/Consumer.java

